apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckart-deployment
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: ckart
  replicas: 2    
  template:
    metadata:
      labels:
        app: ckart
    spec:
      containers:
      - name: ckart-container
        image: lehardocker/couponcode-img:v2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
